function(emeron_set_sanitizers target)
    if(MSVC)
        if(EMERON_ASAN)
            target_compile_options(${target} PRIVATE /fsanitize=address)
        endif()
        return()
    endif()

    set(_flags "")
    if(EMERON_ASAN AND EMERON_TSAN)
        message(FATAL_ERROR "EMERON_ASAN and EMERON_TSAN are mutually exclusive")
    endif()
    if(EMERON_ASAN)
        list(APPEND _flags -fsanitize=address -fsanitize=undefined
                           -fno-omit-frame-pointer -fno-sanitize-recover=all)
    endif()
    if(EMERON_TSAN)
        list(APPEND _flags -fsanitize=thread -fno-omit-frame-pointer)
    endif()
    if(_flags)
        target_compile_options(${target} PRIVATE ${_flags})
        target_link_options(${target} PUBLIC ${_flags})
    endif()
endfunction()
