#include "collect/PerfettoCapture.h"

#include <algorithm>
#include <array>
#include <ctime>
#include <memory>
#include <system_error>
#include <utility>

#include "core/Log.h"
#include "core/StringUtil.h"

namespace em {
namespace {

constexpr const char* kCategory = "perfetto";

void appendFtraceConfig(std::string& out, const PerfettoCaptureOptions& options) {
    const bool wantAtrace = !options.atraceCategories.empty() || !options.atraceApps.empty();
    if (!wantAtrace && !options.ftraceSchedAndFreq) return;

    out += "data_sources: {\n";
    out += "  config {\n";
    out += "    name: \"linux.ftrace\"\n";
    out += "    ftrace_config {\n";

    if (options.ftraceSchedAndFreq) {
        // The scheduling and frequency events that make a trace useful for
        // explaining jank: who ran where, and at what clock.
        for (const char* event : {"sched/sched_switch", "power/suspend_resume",
                                  "sched/sched_process_exit", "sched/sched_process_free",
                                  "task/task_newtask", "task/task_rename",
                                  "sched/sched_waking", "sched/sched_wakeup_new",
                                  "power/cpu_frequency", "power/cpu_idle"}) {
            out += "      ftrace_events: \"";
            out += event;
            out += "\"\n";
        }
    }
    for (const auto& category : options.atraceCategories) {
        out += "      atrace_categories: \"" + category + "\"\n";
    }
    for (const auto& app : options.atraceApps) {
        out += "      atrace_apps: \"" + app + "\"\n";
    }
    out += "    }\n  }\n}\n";
}

void appendProcessStats(std::string& out, const PerfettoCaptureOptions& options) {
    if (!options.processStats) return;
    out += "data_sources: {\n";
    out += "  config {\n";
    out += "    name: \"linux.process_stats\"\n";
    out += "    process_stats_config {\n";
    out += "      scan_all_processes_on_start: true\n";
    out += "      proc_stats_poll_ms: " + std::to_string(options.processStatsPollMs) + "\n";
    out += "    }\n  }\n}\n";
}

void appendSimpleSource(std::string& out, std::string_view name) {
    out += "data_sources: {\n  config {\n    name: \"";
    out += name;
    out += "\"\n  }\n}\n";
}

}  // namespace

std::string makeTraceName() {
    const std::time_t now = std::time(nullptr);
    std::tm parts{};
#if defined(_WIN32)
    localtime_s(&parts, &now);
#else
    localtime_r(&now, &parts);
#endif
    return format("emeron-%04d%02d%02d-%02d%02d%02d.perfetto-trace", parts.tm_year + 1900,
                  parts.tm_mon + 1, parts.tm_mday, parts.tm_hour, parts.tm_min, parts.tm_sec);
}

std::string buildTraceConfig(const PerfettoCaptureOptions& options) {
    if (!options.customConfig.empty()) return options.customConfig;

    std::string out;
    out.reserve(2048);

    out += "# Generated by emeron.\n";
    out += "buffers: {\n";
    out += "  size_kb: " + std::to_string(options.bufferSizeKb) + "\n";
    out += "  fill_policy: RING_BUFFER\n";
    out += "}\n";

    appendFtraceConfig(out, options);
    appendProcessStats(out, options);

    if (options.frameTimeline) {
        // The source behind Perfetto's "Actual Timeline" / jank classification.
        appendSimpleSource(out, "android.surfaceflinger.frametimeline");
    }
    if (options.logcat) appendSimpleSource(out, "android.log");
    if (options.javaHeapGraph) appendSimpleSource(out, "android.java_hprof");

    out += "duration_ms: " + std::to_string(options.durationMs) + "\n";
    return out;
}

PerfettoCapture::PerfettoCapture(DeviceManager& devices) : devices_(devices) {}

PerfettoCapture::~PerfettoCapture() {
    cancel();
    const std::lock_guard lock{threadMutex_};
    if (thread_.joinable()) thread_.join();
}

void PerfettoCapture::probeSupport(ThreadPool& pool) {
    const std::string serial = devices_.selectedSerial();
    if (serial.empty()) {
        supportKnown_.store(false, std::memory_order_release);
        return;
    }

    pool.submit([this, serial] {
        const std::vector<std::string> commands{
            "getprop init.svc.traced",
            "getprop init.svc.traced_probes",
            "getprop persist.traced.enable",
            "which perfetto",
        };

        auto batch = devices_.adb().shellBatch(serial, commands, kAdbNormalTimeout);
        if (!batch) {
            supportMessage_.set("probe failed: " + batch.error().message);
            supported_.store(false, std::memory_order_release);
            supportKnown_.store(true, std::memory_order_release);
            return;
        }
        const auto parts = std::move(batch).value();
        const bool tracedRunning = trim(parts[0]) == "running";
        const bool probesRunning = trim(parts[1]) == "running";
        const bool binaryPresent = !trim(parts[3]).empty();

        std::string message;
        if (!binaryPresent) {
            message = "the `perfetto` binary is not on this device (needs Android 9+)";
        } else if (!tracedRunning || !probesRunning) {
            message = "the device's tracing service (traced) is off; turn it on with "
                      "`adb shell setprop persist.traced.enable 1`";
        } else {
            message = "ready to record (tracing service is running)";
        }

        supported_.store(binaryPresent && tracedRunning && probesRunning,
                         std::memory_order_release);
        supportMessage_.set(std::move(message));
        supportKnown_.store(true, std::memory_order_release);
    });
}

bool PerfettoCapture::start(PerfettoCaptureOptions options,
                            std::filesystem::path outputDirectory) {
    if (busy_.exchange(true, std::memory_order_acq_rel)) return false;

    {
        const std::lock_guard lock{threadMutex_};
        if (thread_.joinable()) thread_.join();
        cancelRequested_.store(false, std::memory_order_release);
        thread_ = std::thread([this, options = std::move(options),
                               outputDirectory = std::move(outputDirectory)]() mutable {
            runCapture(std::move(options), std::move(outputDirectory));
            busy_.store(false, std::memory_order_release);
        });
    }
    return true;
}

void PerfettoCapture::cancel() { cancelRequested_.store(true, std::memory_order_release); }

void PerfettoCapture::runCapture(PerfettoCaptureOptions options,
                                 std::filesystem::path outputDirectory) {
    const std::string serial = devices_.selectedSerial();

    CaptureStatus status;
    status.startedAt = std::chrono::steady_clock::now();
    status.phase = CaptureStatus::Phase::Starting;
    status.configUsed = buildTraceConfig(options);

    if (serial.empty()) {
        status.phase = CaptureStatus::Phase::Failed;
        status.message = "no device selected";
        status_.set(std::move(status));
        return;
    }

    if (options.traceName.empty()) options.traceName = makeTraceName();
    status.remotePath = options.remoteDirectory + "/" + options.traceName;
    status.message = "starting perfetto on device";
    status_.set(status);

    // Running in the foreground (no --background) means the adb shell process
    // lives for the whole capture, so its exit tells us when tracing is done
    // and its stderr carries any config rejection verbatim.
    const std::vector<std::string> args{"shell", "perfetto -c - --txt -o " + status.remotePath};
    auto spawned = devices_.adb().transport().stream(serial, args, /*pipeStdin=*/true);
    if (!spawned) {
        status.phase = CaptureStatus::Phase::Failed;
        status.message = "could not launch perfetto: " + spawned.error().message;
        status_.set(std::move(status));
        return;
    }

    std::unique_ptr<Subprocess> process = std::move(spawned).value();
    if (auto written = process->writeStdin(status.configUsed); !written) {
        status.phase = CaptureStatus::Phase::Failed;
        status.message = "could not send config: " + written.error().message;
        status_.set(std::move(status));
        return;
    }
    process->closeStdin();

    status.phase = CaptureStatus::Phase::Recording;
    status.message = "recording";
    status_.set(status);

    // Drain both pipes while waiting, or a chatty perfetto could fill a pipe
    // buffer and block forever.
    const auto deadline = status.startedAt + std::chrono::milliseconds{options.durationMs} +
                          std::chrono::seconds{20};
    std::array<char, 8192> buffer{};
    std::string deviceOut;
    std::string deviceErr;

    for (;;) {
        if (cancelRequested_.load(std::memory_order_acquire)) {
            process->terminate();
            status.phase = CaptureStatus::Phase::Failed;
            status.message = "cancelled";
            status_.set(std::move(status));
            return;
        }

        bool timedOut = false;
        if (auto n = process->readStdout(buffer, 100, &timedOut); n && *n > 0) {
            deviceOut.append(buffer.data(), *n);
        }
        if (auto n = process->readStderr(buffer, 10, &timedOut); n && *n > 0) {
            deviceErr.append(buffer.data(), *n);
        }

        if (const auto code = process->tryWait()) {
            if (*code != 0) {
                status.phase = CaptureStatus::Phase::Failed;
                status.deviceStderr = deviceErr.empty() ? deviceOut : deviceErr;
                status.message = "perfetto exited with code " + std::to_string(*code);
                EM_LOG_ERROR(kCategory, status.message + ": " + status.deviceStderr);
                status_.set(std::move(status));
                return;
            }
            break;
        }

        const auto now = std::chrono::steady_clock::now();
        if (now >= deadline) {
            process->terminate();
            status.phase = CaptureStatus::Phase::Failed;
            status.message = "perfetto did not finish within the expected window";
            status.deviceStderr = deviceErr;
            status_.set(std::move(status));
            return;
        }

        const double elapsed = std::chrono::duration<double, std::milli>(now - status.startedAt)
                                   .count();
        status.progress = std::min(elapsed / static_cast<double>(options.durationMs), 1.0);
        status_.set(status);
    }

    // --- pull ---------------------------------------------------------------
    status.phase = CaptureStatus::Phase::Pulling;
    status.progress = 1.0;
    status.message = "pulling trace";
    status_.set(status);

    std::error_code ec;
    std::filesystem::create_directories(outputDirectory, ec);
    status.localPath = outputDirectory / options.traceName;

    if (auto pulled = devices_.adb().pull(serial, status.remotePath, status.localPath,
                                          kAdbLongTimeout);
        !pulled) {
        status.phase = CaptureStatus::Phase::Failed;
        status.message = "pull failed: " + pulled.error().message;
        status_.set(std::move(status));
        return;
    }

    // Leaving traces behind fills /data; the device copy has served its purpose.
    (void)devices_.adb().shell(serial, "rm -f " + shellQuote(status.remotePath),
                               kAdbNormalTimeout);

    status.phase = CaptureStatus::Phase::Done;
    status.message = "saved " + status.localPath.string();
    status.deviceStderr = deviceErr;
    EM_LOG_INFO(kCategory, status.message);
    status_.set(std::move(status));
}

}  // namespace em
